"""Displays evolutionary tree page"""

import streamlit as st
from streamlit_echarts import st_echarts
from components.util import fetch_button_callback, initialize_session
from components.tree import get_graph

initialize_session()


@st.dialog("About Common Ancestors")
def common_ancestor_popup():
    """Displays a popup that shows when the user clicks on a common ancestor in the evolutionary tree graph"""
    st.write("""
        ## What are Common Ancestors?
        Any two species on Earth have a common ancestor. Both species evolved from this common
        ancestor a long time ago, and thus share some traits derived from this common ancestor.
             
        ## Tell me about *this* Common Ancestor
        This is an **inferred** common ancestor between two different species.
        The neighborhood joining algorithm, used to create this tree, generates 
        hypothetical ancestors where it predicts an evolutionary event happened.
             
        You can read more about the algorithm here: https://en.wikipedia.org/wiki/Neighbor_joining
        """)


def show_animal_popup(name_of_animal: str):
    """Chooses whether to show the common ancestor popup or the animal details popup"""
    if name_of_animal is None:
        return
    elif ">" in name_of_animal:
        return
    elif "Common Ancestor" in name_of_animal:
        common_ancestor_popup()
    else:
        for animal in st.session_state.animals:
            if animal.name == name_of_animal:
                animal.display_details()


st.title("Evolutionary Tree")
st.write("""
         As you add animals, they will be sorted into an evolutionary tree
         - The **length** of each branch or line represents the evolutionary distance between the two creatures
         - **Hover** over branches to see the exact weight
         - **Click** on a large diamond to see more information about the animal, 
         - Small diamonds correspond to ancestor species generated by the modeling algorithm
         """)

col1, col2 = st.columns(2)

with col1:
    st.button(
        "Create New Animal",
        type="primary",
        on_click=lambda: st.session_state.update({"popup_open": True}),
        width="stretch",
    )
    if st.button(
        "Back to Home Page",
        type="secondary",
        width="stretch",
    ):
        st.switch_page("Home_Page.py")


with col2:
    st.button(
        "Fetch New Animals", type="secondary", on_click=lambda: fetch_button_callback()
    )

graph = get_graph(25, 18)

# This is javascript
graph_events = {
    "click": "function(params) { if (params.componentType === 'series') {return params.name;} }"
}

echarts_options = {
    "backgroundColor": "#c1ceb3",
    "tooltip": {},
    "series": [
        {
            "type": "graph",
            "layout": "force",
            "roam": True,
            "symbol": "circle",
            "force": {
                "repulsion": 400,
                "edgeLength": [20, 80],
            },
            "label": {"show": True, "position": "top"},
            "edgeLabel": {"show": False},
            "lineStyle": {
                "width": 3,
                "curviness": 0.3,
                "type": "solid",
                "color": "#5B3E00",
            },
            "data": graph["data"],
            "links": graph["links"],
            "draggable": True,
        }
    ],
}

clicked_name: dict = st_echarts(
    options=echarts_options, height="500px", events=graph_events
)

if clicked_name:
    show_animal_popup(clicked_name["chart_event"])
